# Generated by Django 4.2 on 2023-04-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_settings_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='numder',
            new_name='phone',
        ),
    ]
