# Generated by Django 4.2 on 2023-04-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_numder_setting_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
    ]
