# Generated by Django 4.2 on 2023-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_setting_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='gallery')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
